- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Saltern
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
  #- Gax # Floof - Remove Gax due to mapping issues, power, access, etc. | M3739 - No current maintainer
  - Rad
  - Meta
  - Kettle # Floof
  - Fland # Floof
  - Train # Floof
  - Amber # Floof
  - talos # Floof!
